# Generated by Django 5.1 on 2026-07-08 06:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
