# Generated by Django 5.1 on 2026-09-30 08:17

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_treatmentplan_options_and_more'),
        ('patients', '0006_patient_recall_interval_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('condition', models.CharField(choices=[('decay', 'Decay / Cavity'), ('filling', 'Filling'), ('crown', 'Crown'), ('root_canal', 'Root Canal'), ('implant', 'Implant'), ('bridge', 'Bridge'), ('missing', 'Missing'), ('watch', 'Watch')], max_length=20)),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_conditions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tooth_number'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'tooth_number'), name='unique_tooth_per_patient')],
            },
        ),
    ]
