# Generated by Django 5.1 on 2026-07-16 03:43

import django.db.models.deletion
import django.db.models.manager
import encrypted_model_fields.fields
import imaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_alter_patient_options_alter_patient_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_type', models.CharField(choices=[('xray', 'X-Ray'), ('photo', 'Photo')], max_length=10)),
                ('image', models.ImageField(upload_to=imaging.models.dental_image_upload_path)),
                ('captured_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_patient', models.BooleanField(default=False, editable=False)),
                ('tooth_number', models.CharField(blank=True, max_length=20)),
                ('caption', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_images', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dental_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['image_type', '-captured_date'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
