# Generated by Django 5.1 on 2026-09-30 08:35

import billing.models
import django.db.models.deletion
import django.db.models.manager
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dentist_name', models.CharField(blank=True, max_length=200, verbose_name='Treating dentist name')),
                ('npi', models.CharField(blank=True, max_length=20, verbose_name='NPI number')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='Tax ID (TIN)')),
            ],
            options={
                'verbose_name': 'Office settings',
                'verbose_name_plural': 'Office settings',
            },
        ),
        migrations.CreateModel(
            name='ClaimDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('letter', models.FileField(upload_to=billing.models.denial_letter_upload_path)),
                ('status', models.CharField(choices=[('denied', 'Denied — needs action'), ('resubmitted', 'Corrected & resubmitted'), ('appealed', 'Appeal sent'), ('approved', 'Approved / paid'), ('closed', 'Closed — not pursuing')], default='denied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('ai_error', models.TextField(blank=True)),
                ('ai_started_at', models.DateTimeField(blank=True, null=True)),
                ('insurer_name', models.CharField(blank=True, max_length=200)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('denial_codes', models.CharField(blank=True, max_length=200)),
                ('amount_denied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appeal_deadline', models.DateField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('appeal', 'Appeal'), ('resubmit', 'Correct & resubmit'), ('not_worth_pursuing', 'Not worth pursuing')], max_length=30)),
                ('summary', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('denial_reason', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('recommendation_reason', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('appeal_letter', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denials', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
