# Generated by Django 5.1 on 2026-09-30 17:50

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_officesettings_claimdenial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdenial',
            name='ai_task',
            field=models.CharField(choices=[('analyze', 'Analyze letter'), ('revise', 'Update letter with review answers')], default='analyze', max_length=10),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='review_answers_json',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='revision_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
