# Generated by Django 5.1 on 2026-09-30 20:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_denial_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Date of service')),
                ('cdt_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^D\\d{4}$', 'Use a CDT code like D2740.')], verbose_name='Procedure code')),
                ('description', models.CharField(max_length=200)),
                ('tooth_number', models.CharField(blank=True, max_length=20, verbose_name='Tooth')),
                ('surfaces', models.CharField(blank=True, max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'ordering': ['service_date', 'pk'],
            },
        ),
    ]
