# Generated by Django 5.1 on 2026-10-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_ai_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
