# Generated by Django 5.1 on 2026-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('anesthetics', 'Anesthetics'), ('instruments', 'Instruments'), ('disposables', 'Disposables'), ('materials', 'Dental Materials'), ('ppe', 'PPE'), ('medications', 'Medications'), ('office', 'Office Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', help_text='e.g. boxes, packs, bottles', max_length=50)),
                ('min_quantity', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
