"""
Django settings for dental_office project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')

# Encrypts PHI fields at rest (medical notes, allergies, insurance info — see
# patients/models.py and clinical/models.py). Losing this key permanently
# loses everything encrypted with it — there is no recovery. Keep a secure,
# durable backup outside of Railway's env var UI.
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')

# Path to the Firebase service account JSON key, used to send push
# notifications for patient messaging (messaging/push.py). Optional — if
# unset or the file doesn't exist, push notifications are silently disabled
# rather than erroring (e.g. a fresh clone without the key configured yet).
FIREBASE_SERVICE_ACCOUNT_PATH = config('FIREBASE_SERVICE_ACCOUNT_PATH', default='')

# S3 storage for dental X-rays/photos (imaging app). Leave AWS_STORAGE_BUCKET_NAME
# unset locally to store uploads on local disk instead. Required in production.
# The bucket must have SSE (server-side encryption) enabled and public access
# blocked — images are only ever served via short-lived signed URLs (see
# AWS_QUERYSTRING_AUTH below).
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_DEFAULT_ACL = None            # bucket/objects stay private
AWS_QUERYSTRING_AUTH = True        # image.url is always a freshly signed, time-limited GET
AWS_QUERYSTRING_EXPIRE = 300       # signed URL lifetime, in seconds
AWS_S3_FILE_OVERWRITE = False

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Railway (and most PaaS) terminate HTTPS at a proxy and forward plain HTTP,
# so Django needs this to know the original request was secure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
# Start with a short HSTS window; raise to 31536000 (1 year) once confirmed
# working on the live domain — HSTS is sticky in browsers once set.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patients',
    'appointments',
    'staff',
    'clinical',
    'billing',
    'inventory',
    'patient_portal',
    'messaging',
    'imaging',
    'demo',
    'anymail',
    'axes',
    'auditlog',
    'django_ratelimit',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'api',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'dental_office.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dental_office.context_processors.user_roles',
                'dental_office.context_processors.demo_mode',
            ],
            # money and provider_name filters, available in every template.
            'builtins': ['dental_office.templatetags.office'],
        },
    },
]

WSGI_APPLICATION = 'dental_office.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (patient-uploaded images). Never use S3 under the test runner, even if
# real AWS credentials happen to be present in a developer's .env — mirrors
# the same 'test' in sys.argv guard used for Firebase in messaging/push.py.
_USE_S3 = bool(AWS_STORAGE_BUCKET_NAME) and 'test' not in sys.argv

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage' if _USE_S3
                    else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
# Jazzmin's admin/base.html references `{% static 'vendor/bootswatch' %}` (a
# bare directory, for its client-side theme-switcher script) rather than an
# actual collected file. Strict manifest lookups 500 on that with "Missing
# staticfiles manifest entry" since it was never collected as a file. This
# tells WhiteNoise to fall back to a best-effort hash instead of raising.
WHITENOISE_MANIFEST_STRICT = False
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'   # only used by the FileSystemStorage fallback above

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'dental_office.backends.CaseInsensitiveModelBackend',
]

# django-axes: lock out after repeated failed logins. Keyed on (IP, username)
# together — locking on username alone lets an attacker bypass the limit by
# rotating cookies/user-agents; locking on IP alone could lock out an entire
# shared office network for one bad login.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [['ip_address', 'username']]
# Behind Railway's proxy, REMOTE_ADDR is the proxy, not the visitor; without
# this every attempt looked like a new address and nothing ever locked.
AXES_CLIENT_IP_CALLABLE = 'dental_office.security.client_ip'
AXES_LOCKOUT_CALLABLE = 'dental_office.security.lockout_response'

# django-ratelimit flags the default LocMemCache as "not a shared cache",
# which matters for multi-worker/multi-dyno deployments (each process would
# rate-limit independently). Gunicorn here runs a single worker (see
# Procfile — no --workers flag), so LocMemCache genuinely is shared across
# every request this app serves. Revisit this (add Redis, stop silencing)
# if the Procfile ever adds multiple workers.
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003']

# The test suite's cumulative login calls across many test classes exceed
# the login endpoint's rate limit within a single test run; this is
# django-ratelimit's own documented way to disable limiting under `manage.py
# test` without weakening it in production.
RATELIMIT_ENABLE = 'test' not in sys.argv
# Same proxy problem as AXES_CLIENT_IP_CALLABLE above; and a friendly
# "please wait" page (HTTP 429) instead of a bare 403 when a limit is hit.
RATELIMIT_IP_META_KEY = 'dental_office.security.client_ip'
RATELIMIT_VIEW = 'dental_office.security.ratelimited'

# Mobile app API (JWT-authenticated, separate from the session-based web app —
# existing web views are untouched by this).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Email — prints to console by default; set EMAIL_BACKEND to Anymail's Resend
# backend in production. Railway (like many PaaS hosts) blocks outbound SMTP
# ports entirely, so Resend is used via its HTTP API instead of SMTP.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@dentaloffice.com')
# The site's public address, for portal links in emails. The daily email job
# has no web request to read it from. On Railway the web service has
# RAILWAY_PUBLIC_DOMAIN and the cron service RAILWAY_SERVICE_WEB_URL; set
# SITE_URL once the office has its own domain.
_railway_host = config('RAILWAY_PUBLIC_DOMAIN', default='') or config('RAILWAY_SERVICE_WEB_URL', default='')
SITE_URL = config('SITE_URL', default=f'https://{_railway_host}' if _railway_host else 'http://localhost:8000').rstrip('/')
ANYMAIL = {
    'RESEND_API_KEY': config('RESEND_API_KEY', default=''),
}

# AI insurance-denial helper (billing/ai.py). Without a key, uploads still work
# but the analysis fails with a message explaining how to set it up.
# .strip(): a key pasted into a hosting dashboard easily picks up a trailing
# newline, which HTTP rejects as an illegal header value.
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='').strip()
# Sending PHI to Anthropic requires a signed BAA. Until then this stays False:
# the app shows a demo-mode warning and staff must confirm each uploaded letter
# contains no real patient information.
AI_PHI_ALLOWED = config('AI_PHI_ALLOWED', default=False, cast=bool)
# Analysis takes 30-90s, so it runs in a background thread; tests run it inline.
ANALYZE_DENIALS_IN_BACKGROUND = 'test' not in sys.argv
# Max AI denial runs per day across all users (superusers exempt). 0 = no cap.
AI_DAILY_LIMIT = config('AI_DAILY_LIMIT', default=0, cast=int)

# --- Demo phase -------------------------------------------------------------
# BEFORE REAL PATIENTS: set REQUIRE_2FA=True and DEMO_MODE=False on Railway.
# Staff must set up 2FA before using the app. Turned off while the live site
# is a public demo; accounts that already have 2FA are still asked for a code.
REQUIRE_2FA = config('REQUIRE_2FA', default=True, cast=bool)
# Public demo: one-click demo logins, a 'fictional data' banner, the demo
# practice reloaded nightly (wiping all patient data), and no real emails sent.
DEMO_MODE = config('DEMO_MODE', default=False, cast=bool)
if DEMO_MODE:
    # Demo patients have made-up addresses; print emails to the logs instead.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin theme (django-jazzmin)
JAZZMIN_SETTINGS = {
    "site_title": "Dental Office Admin",
    "site_header": "Dental Office",
    "site_brand": "Dental Office",
    "welcome_sign": "Welcome to the Dental Office admin",
    "copyright": "Dental Office",
    "search_model": ["patients.Patient", "appointments.Appointment"],
    "topmenu_links": [
        {"name": "Back to Site", "url": "/", "permissions": []},
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "patients.Patient": "fas fa-tooth",
        "patients.MedicalAlert": "fas fa-exclamation-triangle",
        "appointments.Appointment": "fas fa-calendar-check",
        "appointments.AppointmentRequest": "fas fa-inbox",
        "appointments.ReminderLog": "fas fa-bell",
        "staff.StaffProfile": "fas fa-id-badge",
        "staff.TOTPDevice": "fas fa-shield-alt",
        "clinical.TreatmentRecord": "fas fa-notes-medical",
        "clinical.TreatmentPlan": "fas fa-clipboard-list",
        "billing.Invoice": "fas fa-file-invoice-dollar",
        "billing.Payment": "fas fa-money-bill-wave",
        "inventory.SupplyItem": "fas fa-box",
        "patient_portal.PatientInvite": "fas fa-envelope-open-text",
        "imaging.DentalImage": "fas fa-x-ray",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "accent": "accent-primary",
    "theme": "flatly",
    "dark_mode_theme": None,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
