# Generated by Django 5.1 on 2026-07-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_reminderlog'),
        ('patients', '0003_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='patients.patient'),
        ),
    ]
