# Generated by Django 5.1 on 2026-09-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointmentrequest_status'),
        ('patients', '0006_patient_recall_interval_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('no_email', 'No Email')], default='sent', max_length=10)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('error_message', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_notices', to='patients.patient')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
