# Generated by Django 5.1 on 2026-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_recallnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
