# Generated by Django 5.1 on 2026-10-02 03:28

import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_scheduled_job_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='phone',
            field=models.CharField(max_length=20, validators=[patients.validators.validate_phone]),
        ),
    ]
