# Generated by Django 5.1 on 2026-10-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='appointments.appointment'),
        ),
    ]
