# Generated by Django 5.1 on 2026-06-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('allergy', 'Allergy'), ('medication', 'Medication'), ('condition', 'Medical Condition'), ('other', 'Other')], default='allergy', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_alerts', to='patients.patient')),
            ],
            options={
                'ordering': ['-severity', 'alert_type'],
            },
        ),
    ]
