# Generated by Django 5.1 on 2026-07-08 06:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
