# Generated by Django 5.1 on 2026-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_options_alter_patient_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recall_interval_months',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Every 3 months'), (4, 'Every 4 months'), (6, 'Every 6 months'), (12, 'Every 12 months')], default=6, help_text='How often this patient should come back for a cleaning/checkup.', verbose_name='Cleaning recall interval'),
        ),
    ]
