# Generated by Django 5.1 on 2026-10-02 03:28

import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_recall_interval_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[patients.validators.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[patients.validators.validate_phone]),
        ),
    ]
